stages:
  - build
variables:
  CONTAINER_REGISTRY: "https://fsatertyshnyiregistry.azurecr.io"
  DOCKER_REPOSITORY: "fsatertyshnyiregistry.azurecr.io"
  IMAGE_NAME: "app"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://127.0.0.1:2375
  DOCKER_TLS_VERIFY: ""
  DOCKER_TLS_CERTDIR: ""
build_image:
  stage: build
  tags:
    - fsa-tertyshnyi
  image: docker:dind
  services:
    - docker:latest
  before_script:
    - until docker info &>/dev/null ; do sleep 2 && echo "Testujem pripojenie na Docker deamon (dind)" ; done
    - export IMAGE_VERSION="${CI_JOB_ID}-${CI_COMMIT_SHORT_SHA}"
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$CONTAINER_REGISTRY"
    - docker build -t "$DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_VERSION" -t "$DOCKER_REPOSITORY/$IMAGE_NAME:latest" .
    - docker push "$DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_VERSION"
    - docker push "$DOCKER_REPOSITORY/$IMAGE_NAME:latest"
  only:
    - main
