stages:
  - build-backend
  - build-frontend

variables:
  CONTAINER_REGISTRY: "https://fsatertyshnyiregistry.azurecr.io"
  DOCKER_REPOSITORY: "fsatertyshnyiregistry.azurecr.io"
  IMAGE_NAME_BACKEND: "fsa-backend"
  IMAGE_NAME_FRONTEND: "fsa-frontend"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://127.0.0.1:2375
  DOCKER_TLS_VERIFY: ""
  DOCKER_TLS_CERTDIR: ""

#build_backend:
#  stage: build-backend
#  tags:
#    - fsa-tertyshnyi
#  image: docker:dind
#  services:
#    - docker:latest
#  before_script:
#    - until docker info &>/dev/null ; do sleep 2 && echo "Testujem pripojenie na Docker deamon (dind)" ; done
#    - export IMAGE_VERSION="backend-${CI_JOB_ID}-${CI_COMMIT_SHORT_SHA}"
#  script:
#    - cd backend
#    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$CONTAINER_REGISTRY"
#    - docker build -t "$DOCKER_REPOSITORY/$IMAGE_NAME_BACKEND:$IMAGE_VERSION" -t "$DOCKER_REPOSITORY/$IMAGE_NAME_BACKEND:latest" .
#    - docker push "$DOCKER_REPOSITORY/$IMAGE_NAME_BACKEND:$IMAGE_VERSION"
#    - docker push "$DOCKER_REPOSITORY/$IMAGE_NAME_BACKEND:latest"
#  only:
#    - main

build_frontend:
  stage: build-frontend
  tags:
    - fsa-tertyshnyi
  image: docker:dind
  services:
    - docker:latest
  before_script:
    - until docker info &>/dev/null ; do sleep 2 && echo "Testujem pripojenie na Docker deamon (dind)" ; done
    - export IMAGE_VERSION="frontend-${CI_JOB_ID}-${CI_COMMIT_SHORT_SHA}"
  script:
    - cd frontend
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$CONTAINER_REGISTRY"
    - docker build -t "$DOCKER_REPOSITORY/$IMAGE_NAME_FRONTEND:$IMAGE_VERSION" -t "$DOCKER_REPOSITORY/$IMAGE_NAME_FRONTEND:latest" .
    - docker push "$DOCKER_REPOSITORY/$IMAGE_NAME_FRONTEND:$IMAGE_VERSION"
    - docker push "$DOCKER_REPOSITORY/$IMAGE_NAME_FRONTEND:latest"
  only:
    - main
