apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 4200
      targetPort: http
  type: ClusterIP
  # loadBalancerIP: "52.138.207.76"