spring:
  datasource:
    url: jdbc:mysql://localhost:3306/streaming_main
    username: root
    password: MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: streaming_main
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    mapping-resources:
      - persistence/streaming-orm.xml

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080

logging:
  level:
    org.springframework.security: debug