server:
  port: 8080
#  servlet:
#    context-path: /streaming-platform

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fsa
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    name: fsa-db
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    mapping-resources:
      - persistence/streaming-orm.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/FSA

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.security: debug

keycloak:
  url: http://localhost:8081
  realm: FSA
  client-id: fsa-client
  client-secret: "**********"

